/** @format */

import type { Metadata } from "next";
import "./globals.css";
import { CompletionProvider } from "@/context/CompletionContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={``}
				data-new-gr-c-s-check-loaded="14.1233.0"
				data-gr-ext-installed=""
			>
				<CompletionProvider>{children}</CompletionProvider>
			</body>
		</html>
	);
}
